version: '3.8'

services:
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pytest:
    build: .
    command: poetry run pytest
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - postgres

volumes:
  postgres_data: