# Generated by Django 5.2 on 2025-04-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user1', models.CharField(blank=True, max_length=100, null=True)),
                ('user2', models.CharField(blank=True, max_length=100, null=True)),
                ('user3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
